# Generated by Django 4.2.1 on 2023-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='photo',
            name='version',
            field=models.CharField(choices=[('photo', 'photo'), ('portraite', 'portraite'), ('artwork', 'artwork')], default='photo', max_length=200),
        ),
    ]
