# Generated by Django 4.2.1 on 2023-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_delete_type_photo_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='author',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='version',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(choices=[('photo', 'photo'), ('portrait', 'portrait'), ('artwork', 'artwork')], default='photo', max_length=200),
        ),
    ]
