# Generated by Django 4.2.1 on 2023-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_emailform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='deslike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
