# Generated by Django 4.2.1 on 2023-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_photo_deslike_photo_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='deslike',
            new_name='dislike',
        ),
    ]
